import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Container from "@/Container/Container";
import Navbar from "@/Navigation/Navbar";
import Sidebar from "@/Navigation/Sidebar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DevTrack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen">
          <aside className="w-64 border[#1D1D29] border-r"> 
            <Sidebar />
          </aside>
          <div className="flex flex-1 flex-col bg[">
              <Navbar />
            <main className="flex-1  ">
              <Container>
                {children}
              </Container>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
